project:
  type: website
  output-dir: docs

website:
  title: "Kiarra Pearson's Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - portfolio.qmd
      - Analysis Walkthrough.qmd
      
  page-footer: 
    left: "Copyright 2021, Norah Jones" 
    right: 
      - icon: github
        href: https://github.com/kiarrapearson
      - icon: twitter 
        href: https://twitter.com/KiarraaMonet 
  
format:
  html:
    theme: minty
    css: styles.css
    toc: true




