---
title: "News Writing Piece"
author: "Kiarra Pearson"
editor: visual
---

# Higher education professionals working to sustain the mission of historically Black colleges and universities

## By Kiarra Pearson

Historically Black colleges and universities (HBCUs) were established with the goal of empowering Black people by providing more than simply a college education.

Several university officials representing  HBCUs gathered as panelists for a webinar hosted by Diverse: Issues in Higher Education, a platform used as a news source for insightful information about issues in higher education. The panelists shared their findings on how universities can continue upholding their mission of creating a space for support and learning, declaring the importance of HBCUs to state leaders, building endowments, and engaging stakeholders. 

While the COVID-19 pandemic is slowly dying down, higher education professionals believe HBCUs should be focusing on strategic development and storytelling. 

"​When dealing with a crisis, time for input, criticism, and listening is often limited. President of Benedict College in South Carolina, Dr. Roslyn Clark Artis said,"We have to do what is important at the moment."

"Those are the muscles we must re-engage as we emerge from COVID-19. More consideration is required."Developing a strategic plan, objectives, outcomes, and goals demands everyone's buy-in, contribution, thoughtfulness, and understanding of the rules of engagement," she noted.

Dr. Charlie Nelms, at North Carolina Central University and President-in-Residence at the United Negro College Fund, advocated confining strategic plans to no more than 15 pages, listening to all stakeholders for input, and being open to new ideas.

Dr. Charlie Nelm is a physician that practices in the United States. "Many things that we identify as traditions are really unhealthy habits," Nelms told the moderator, Dr. Jamal Watson. "Just because we did things that way doesn't imply it's the best way. It is critical to plan. I don't believe you can create an administrative plan on your own; you need active participation and engagement."

Former Winston-Salem State University chancellor and author of Saving Black Colleges: Leading Change in a Complex Organization, Dr. Alvin Schexnider, agreed with the statement.

"Accountability means being direct about expectations and having a tool to track how well you've met those objectives," according to Schexnider. "As a higher education institution in a competitive climate, be particular and extremely clear about what you aim to achieve."

The experts agreed that institutions need to improve their storytelling abilities. While all HBCUs share the same goal, according to Nelms, "legislative boards and state board governments must recognize that."

"That's why it's important to continually engage them to experience what it's like on campus to understand the true mission, focus, and successes of our various institutions," said Nelms.

Artis stated that one of her responsibilities as president is to educate others about the importance of her institution in the community's development.

"HBCUs revolutionize wrap-around service---we meet students where they are, create solutions to complex problems on a daily basis," said Artis. "It changes the assessment conversation when we start centering student experience."

During the peak of the pandemic, students at Benedict College who needed healthcare, internet, housing, or financial support used an application to get help. The data they provided was utilized to create a dataset specific to Benedict College students, which was used to better understand their requirements and track the college's success in overcoming hurdles.

"Nearly 80% of the students at my university receive the Pell grant," said Artis, indicating that such students' FAFSAs show a significant financial need."We are taking the holistic approach, we listen and look beyond the numbers. We strive to understand where our students are in a way that we can  intervene and prevent several generations of poverty or health problems caused by discrimination. 

Nelms encouraged HBCU officials to continue relentlessly in their efforts to keep their schools fresh in the minds of people in charge of higher education funds in order to improve financial resources accessible to high-need students.

"We need to educate legislators, keep the pressure on them, point out historical inequalities, and urge that they make the necessary expenditures," Nelms added. "It's critical for legislators at all levels to recognize that funding isn't a luxury; it's a necessity."Unmet financial pledges and lagging endowments have plagued historically black colleges and universities for decades, but those imbalances may be changing thanks to the efforts of HBCU alumni in leadership positions in several states. Maryland HBCUs won a \$577 million lawsuit against the state for persistent underfunding in 2021.

All three speakers were delighted to be graduates of historically black colleges and universities. Their personal experiences, they added, fuel their desire to see that these organizations survive.

"We wouldn't be having this conversation if it weren't for Grambling State," Schexnider added, complimenting his alma mater's importance in his current life. "We understand the importance of these institutions." They're underestimated and underutilized, and we'll do everything we can to highlight their relevance to Black people's future for as long as we can."
